### ISSUE TITLE
Dependency and User Pass Auth

### ISSUE THREAD

**Issue by markrey** [hardillb/node-red-contrib-ldap-auth#1]
Hi Ben,

Thank you for developing the library.
I am currently trying to improve based in the same. 
Couple of issues
1. Dependencies are old 
2. Only LDAP Anonymous access ( i am trying to add user pass )

Do you have updated one at local level ? Or not working on it anymore ?

**Comment by hardillb** [comment]
No, it was written for something specific and I've not needed it since, do
it's not been touched.

Pull requests will be looked on favourably
