### ISSUE TITLE
Permissions for users after auth

### ISSUE THREAD

**Issue by tom-vianai** [hardillb/node-red-contrib-ldap-auth#11]
How do I control the permissions for the authenticated users.  I'm able to login but get a blank page for the most part and if I go to /flows I get unauthorized

**Comment by hardillb** [comment]
You are going to need to supply a **LOT** more detail before I'm going to be able to offer any help with anything here.

**Comment by tom-vianai** [comment]
I have setup and copied my setting.js to the /data dir on the docker hub image (FROM nodered/node-red:2.2.0-14) and it now prompts for a user name and pw, and does correctly verify against my ldap.  But after logging in all I see at  the top is the NodeRed icon in the menu bar.  If I set the anon_read: true flag I do see the palette and other items in the UI.  This leads me to believe I need to set the permissions for user that authenticate similar to what is done in basic user/pw example in the settings file
    // adminAuth: {
    //    type: "credentials",
    //    users: [{
    //        username: "admin",
    //        password: "$2b$08$33BFdDsDCJcEuX5VYlPYBOvVHayC.JAdAhDHX.FqYk6weynvMMhCK",
    //        permissions: "*"
    //    }]
    // },

**Comment by tom-vianai** [comment]
Can I add permissions to the example you provide so the content will show in the UI:
adminAuth: require('node-red-contrib-ldap-auth').setup({
  uri:'ldap://url.to.server',
  base: 'ou=group,o=company.com',
  filterTemplate: 'mail={{username}}',
  bind_dn: 'cn=authuser,o=company.com',
  bind_pw: 'yourlittlesecret',
}),

**Comment by hardillb** [comment]
No, all authenticated users get full read/write access. You can allow unauthenticated users to have read only access by setting the `anon_read: true` option as mentioned at the end of the README.md

The failure to load the page is nothing to do with the LDAP module, you have a different problem, most likely a caching problem.

Also unless you have modified the `httpAdminRoot`you should not be pointing a browser to `/flows` that is an API endpoint, the editor adds a Bearer token to the request.
