### ISSUE TITLE
LDAP ssl certificate

### ISSUE THREAD

**Issue by jualfoar** [hardillb/node-red-contrib-ldap-auth#17]
Hi. thanks for your work! 
any way to tell the certificat to use? 

`Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}`

also a way to crypt the password? 

Thank you!

**Comment by hardillb** [comment]
From the [README.md](https://github.com/hardillb/node-red-contrib-ldap-auth#certificate-verification) You can disable validation of the LDAP servers TLS certificate by adding the  `no_verify_ssl` to the `setup()` args with a value of `true`.

And no, you must supply a plain text password, but if people have access to your `settings.js` then they basically have full access to your Node-RED instance already.

**Comment by jualfoar** [comment]
With the value `no_verify_ssl` to true I have this: 
`Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}`

**Comment by hardillb** [comment]
In that case you are going to need to supply an order of magnitude more information about:

1. How you have configured Node-RED
2. Details about the certificate your LDAP server is using.

**Comment by jualfoar** [comment]
Thank you!
is there a way to add the  auth to `httpNodeAuth `? 

I copied and pasted form `adminAuth ` and doesnt work. 

`Failed to get https settings: TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at basicAuthMiddleware (C:\Node-Red\Node-Red_Sources\npm\node_modules\node-red\red.js:365:18)
    at C:\Node-Red\Node-Red_Sources\npm\node_modules\node-red\red.js:412:39`

**Comment by hardillb** [comment]
I'm sorry, but this whole issue is like a random stream of conciousness.

You've not supplied any of the information I've asked for and are now talking about something totally different. If you want help you need to supply the things I asked for. If you've solved the original problem then you need to mention that not just totally change course.

No, this will not work with `httpNodeAuth`, that is a totally different API to `adminAuth` you can not just swap one for another.

I'm going to close this issue now.
