### ISSUE TITLE
Error: Cannot find module 'when'

### ISSUE THREAD

**Issue by rossigee** [hardillb/node-red-contrib-ldap-auth#2]
When configured as per README.md, my node-red does not start...

```
Error loading settings file: /root/.node-red/settings.js
Error: Cannot find module 'when'
```

I suspect that 'when' is an old dependency of an old dependency, iyswim.

**Comment by rossigee** [comment]
On closer inspection it's a direct dependency, but not listed in the 'requires' part of the package.json.

**Comment by hardillb** [comment]
OK, thanks. It's been ages since I needed this code. I'll see if I can push an update a little later today

**Comment by hardillb** [comment]
ahh, I see the pull request, I'll give the once over and merge and push a new version
