### ISSUE TITLE
[question] Trying to connect to online-ldap-test-server

### ISSUE THREAD

**Issue by roalcantara** [hardillb/node-red-contrib-ldap-auth#4]
Hi there!

First of all, congratulation for this excellent Node! Quite useful! ☺️

I'm pretty much rookie in using both node.js and LDAP, and I've been trying to connect to the [online-ldap-test-server](http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/) without success.

I'm not quite sure of what should go on `filterTemplate` and I believe this could be the problem.

This is what I've been trying to do so far:
```
    adminAuth: require('node-red-contrib-ldap-auth').setup({
      uri:'ldap://ldap.forumsys.com',
      base: 'dc=example,dc=com',
      filterTemplate: 'ou=scientists'
    }),
```

But, even using the username `newton` and pwd: `password` (as suggested), the authentication still fails miserably.

<img width="617" alt="screen shot 2017-05-30 at 4 41 29 pm" src="https://cloud.githubusercontent.com/assets/361140/26601822/c78e84c2-4557-11e7-9d8c-7b487c9bb6ad.png">

Any ideas of what I'm doing wrong?

Also, is there any way to enable some DEBUG mode, in order to obtain more detail from the authentication process failures?

Cheers.

**Comment by hardillb** [comment]
The filterTemplate needs to be a mustashe template that includes the username field to match against the ldap.

In the case of the test server it needs to be:

```
adminAuth: require('node-red-contrib-ldap-auth').setup({
      uri:'ldap://ldap.forumsys.com',
      base: 'ou=scientists,dc=example,dc=com',
      filterTemplate: 'uid={{username}}'
    }),
```

This will match against scientists and not mathematicians.

**Comment by roalcantara** [comment]
Hi @hardillb,

Thank you so much for your reply. It has shed a huge light on my problem. 😁

Yet, the only way that I could get this working, was by getting rid of the group.

That is, this works (at least, in my environment) with any user:
```
    adminAuth: require('node-red-contrib-ldap-auth').setup({
      uri:'ldap://ldap.forumsys.com',
      base: 'dc=example,dc=com',
      filterTemplate: 'uid={{username}}'
    }),
```
Whereas I couldn't get this working (with mathematicians nor any user):
```
    adminAuth: require('node-red-contrib-ldap-auth').setup({
      uri:'ldap://ldap.forumsys.com',
      base: 'ou=mathematicians,dc=example,dc=com',
      filterTemplate: 'uid={{username}}'
    }),
```
Neither do this  (with scientists nor any user):
```
    adminAuth: require('node-red-contrib-ldap-auth').setup({
      uri:'ldap://ldap.forumsys.com',
      base: 'ou=scientists,dc=example,dc=com',
      filterTemplate: 'uid={{username}}'
    }),
```
Just for disclosure, my environment is:
```
30 May 18:44:56 - [info] Node-RED version: v0.16.2
30 May 18:44:56 - [info] Node.js  version: v6.10.2
30 May 18:44:56 - [info] Darwin 16.6.0 x64 LE
...
```
and:
```
$ npm -g ls | grep ldap
  node-red-contrib-ldap-auth@0.0.3
```
Nevertheless, thanks a bunch for your help.
