### ISSUE TITLE
Users Permissions?

### ISSUE THREAD

**Issue by roalcantara** [hardillb/node-red-contrib-ldap-auth#5]
Hi there!

Once again, thank you so much for this incredible node.

Now, I need to set permissions for each authenticated user.

At first, the 2 basic permissions (full access and read-only) might do. Yet, I will probably need a more granular level of permissions, for the near future.

I've noticed that node-red is already prepared for [both approaches](http://nodered.org/docs/security).

However, it seems to me that the node-red-contrib-ldap-auth [sets the full-access permission by default](https://github.com/hardillb/node-red-contrib-ldap-auth/blob/master/node-red-contrib-ldap-auth.js#L71) when a user is successfully authenticated, right?

I was considering to send a PR trying to handle this scenario, setting the permission based on some information from the LDAP.

But first, I'd like to know what are your thoughts about this and if you've got any suggestions about it.

Thanks a bunch.

**Comment by hardillb** [comment]
What you see is what you get. PR will be looked at
