### ISSUE TITLE
Allow checking if user is in groupOfUniqueNames

### ISSUE THREAD

**Issue by luketainton** [hardillb/node-red-contrib-ldap-auth#8]
I'd like to use a groupOfUniqueNames for authorisation, where each user in the group is specified as:
`uniqueMember: <DN>`

Is this possible already?

**Comment by hardillb** [comment]
No, not at the moment.

I'd be happy to look at pull request to add support

**Comment by hardillb** [comment]
Actually assuming you have `memberOf` support in your LDAP instance then you should be able to do it with the right filter

Assuming the dn of group is `cn=test,ou=groups,dc=example,dc=com` you should be able to do something like this:
```
adminAuth: require('node-red-contrib-ldap-auth').setup({
  uri:'ldap://url.to.server',
  base: 'ou=users,dc=example,dc=com',
  filterTemplate: '(&(mail={{username}})(memberOf=cn=test,ou=groups,dc=example,dc=com))'
}),
```

**Comment by luketainton** [comment]
This worked for me - thanks for the help!
